### ISSUE TITLE
Develop Purpose Page

### ISSUE THREAD

**Issue by Gennalynb123** [sanvi1855544/p3-avatar#11]
- [Purpose page](https://github.com/sanvi1855544/p3-avatar/commit/d7651c164f4d02a64c31bd02086f4aecbf0654a8)
- [Links](https://github.com/sanvi1855544/p3-avatar/commit/5139beb2991b7682ee36d27d01f81753ef969646)

**Comment by xu-ellen** [comment]
[Tangibles](https://github.com/sanvi1855544/p3-avatar/commit/d7651c164f4d02a64c31bd02086f4aecbf0654a8)
