### ISSUE TITLE
Review Ticket - Week 1 Project Approval

### ISSUE THREAD

**Issue by Gennalynb123** [sanvi1855544/p3-avatar#14]
grades in comments

**Comment by SlimeyTurtles** [comment]
### Crossover Team Grading
| Name | Group | TPT |
| --- | --- | --- |
| Genalynn | 5/5 | 3/3 |
| Kashish |  | 3/3 |
| Ellen | 5/5 | 3/3 |
| Sanvi | 5/5 | 3/3 |

**Comment by jm1021** [comment]
Avatar - Gennalyn 4.9/5
* Action bring “sigma” into Wiki, designs are nice 1/1
* Wires correlate with 10 - 12 ideas 1/1
* Management plan, deployment, two updates per week 2/2
* Add 10-12 ideas to scrum board .9/1

**Comment by jm1021** [comment]
I would have liked to see a link to your TPT.  -0.1..  Total score is 7.8/8
