### ISSUE TITLE
Individual About Me Page (Ellen)

### ISSUE THREAD

**Issue by Gennalynb123** [sanvi1855544/p3-avatar#2]
Develop your individual about me page with the following requirements:

- [x] [extend from layout](https://github.com/sanvi1855544/p3-avatar/commit/11c4be03976ba9a0641964f5ca578b3695f025fb)
- [x] [special customization (color pallet, background, etc.)](https://github.com/sanvi1855544/p3-avatar/commit/2a04be9f6a0e54dcde54fdf2f2a9f05e68a1ddbc)
- [x] [picture of yourself with a mask on that toggles to a picture of your choice](https://github.com/sanvi1855544/p3-avatar/commit/678e73b3138cb77473d59e4f5b7b0f4f3fa99d0f)
- [x] [pull or show data (Web API) with information of interest](https://github.com/sanvi1855544/p3-avatar/commit/d3211b54f5a0baec2df942375cd4319d1392439b)
- [x] [establish links to your pair share journal and other key indicators of your work/progress](https://github.com/sanvi1855544/p3-avatar/commit/678e73b3138cb77473d59e4f5b7b0f4f3fa99d0f)

**Comment by xu-ellen** [comment]
[Individual Pages](https://github.com/sanvi1855544/p3-avatar/tree/main/templates)
