### ISSUE TITLE
Week 5/7 Review Ticket

### ISSUE THREAD

**Issue by Gennalynb123** [sanvi1855544/p3-avatar#32]
**CB: Crossover team (Team Microsoft Tech Support)**

(One minute video commented by crossover team)

- [x] PBL Key Features
- [agility game](https://github.com/sanvi1855544/p3-avatar/commit/168826bd9ea70760a18f3187a9626148d8117352)
- [interactive quiz](https://github.com/sanvi1855544/p3-avatar/commit/0cd16b6f52398f08671e25395b654fa00a5de1e8)
- [interactive quiz #2](https://github.com/sanvi1855544/p3-avatar/commit/1a0e2baae533c758598343932e1f3674fd13d87f)
- home
- [purpose page
](https://github.com/sanvi1855544/p3-avatar/commit/d7651c164f4d02a64c31bd02086f4aecbf0654a8)
- ([Bending game - copy of life game in TT7](https://github.com/sanvi1855544/p3-avatar/commit/fd71eaac2770a812bbfa2244fdae7113a0ce0f94))
- [x] Github pages/Jekyll/Wiki
- [Wiki](https://github.com/sanvi1855544/p3-avatar/wiki), Vocab [(Ellen, Sanvi, Gennalyn)](https://github.com/sanvi1855544/p3-avatar/wiki/Midterm-Vocab-and-Competency), [Kashish](https://github.com/sanvi1855544/p3-avatar/wiki/Midterm-Vocab-(Kashish))
- jekyll theme ([themes](https://github.com/sanvi1855544/p3-avatar/commit/f688e279a7a10786defe03cd2df35e5febd283e1)) 
- [config.yml](https://github.com/sanvi1855544/p3-avatar/commit/eb1d0fba9587ce1bc0cb4a3739008b3c54e28887)

- [x] [Bootstrap](https://github.com/sanvi1855544/p3-avatar/commit/0cd16b6f52398f08671e25395b654fa00a5de1e8)
- Bootstrap with [quiz 1](https://github.com/sanvi1855544/p3-avatar/commit/0cd16b6f52398f08671e25395b654fa00a5de1e8#diff-1bd1118ce916d80442bc42c39c4547b00a9a6baee9849d78342c6b5869159f88R6), [quiz 2](https://github.com/sanvi1855544/p3-avatar/commit/1a0e2baae533c758598343932e1f3674fd13d87f)

- [x] [Asynch Operation](https://github.com/sanvi1855544/p3-avatar/commit/f99a515ae085c2fc4ac35e4b3326ed0bd615bcc5)
- [x] [CRUD in Database](https://github.com/sanvi1855544/p3-avatar/commit/666021f353b21d2ffc8de29c3da37da6b8ac9b40)

Extra:
- [x] Blueprint ([Sanvi,](https://github.com/sanvi1855544/p3-avatar/commit/f06ba88cd4189fb4e7324594c57ca18cdb826bce) [Ellen, Kashish, Gennalyn](https://github.com/sanvi1855544/p3-avatar/commit/4dfddfd92c9102dbe1c268bfcba3d61fd8c723ed))
- [x] [Formatted Search Bar](https://github.com/sanvi1855544/p3-avatar/commit/d83f84ea62bdb82d4af3652c1c9bd0c2509af88b)

**Comment by AkhilNandhakumar** [comment]
### Score: 5.75/6
Reason:
User interface/css of the site could be better, some of the text and formatting was a bit rough (quiz and games pages, navbar items)
